INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES (1, 'Chime', 'Sigrist');
INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES (2, 'Aydin', 'Öcal');
INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES (3, 'Alina', 'Spangenberg');
INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES (4, 'Nils', 'Oriet');
INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES (5, 'Anthony John', 'Mamaril');