@startuml
'https://plantuml.com/sequence-diagram

hide footbox
actor ":Registered User" as user
participant ":System" as system
user -> system: loadTemplates
system  --> user: all templates
...

user -> system: "createNewTemplate"
system --> user: "empty Template with available data formats"
...
loop
    user -> system: "add(row)"
end
...
user -> system: "saveTemplate"
system --> user: "savedTemplate"

@enduml